Jade
marmikpatel19/Agent pull request #17
Opened 2024-07-13 10:03 UTC by JadeEmm

Please review updates to the pages for pricing, become an agent,  contact us and home

2024-07-13 16:43 UTC, marmikpatel19 requested changes
lots of great work!

In the future, please make a branch & pr for each feature instead of doing everything on one branch and merging in one pr. This way we have modularity and others can keep up or take over work. Also, please make your PR names descriptive (e.g., "contact us page")

Left some feedback for you to review. also, you have some merge conflicts that you need to resolve before merging

2024-07-13 16:43 UTC, marmikpatel19 commented on app/page.tsx
> +    <Link className="font-bold text-lg sm:text-2xl" href="/signup">Connect with an Agent</Link>
is /signup a real page? I don't remember up making a page. we should link directly to the auth flow

2024-07-13 16:43 UTC, marmikpatel19 commented on app/page.tsx
> +      <h2 className="text-3xl font-bold mb-0">Join the Agent Success Story</h2>
is this meant to be a button? and shouldn't our marketing site tailor to seekers and not agents? we can have a less public page for agents.

2024-07-13 16:43 UTC, marmikpatel19 commented on components/BecomeAnAgent.tsx
nice work!

2024-07-13 16:43 UTC, marmikpatel19 commented on components/ContactUs.tsx
> +              <li className="list-item"><i className="fa fa-phone fa-2x"><span className="contact-text phone"><a href="tel:XX" title="Give me a call">(XXX) XXX-XXXX</a></span></i></li>
let's leave out the placeholders for now. we can add them in as needed

2024-07-13 16:43 UTC, marmikpatel19 commented on components/ContactUs.tsx
> +                <i className="fa fa-paper-plane"></i><span className="send-text">SEND</span>
just UI? the contact form doesn't link anywhere

can you make it functional? let's keep it simple. let's link to a google spreadsheet for now or even simpler just send us an email 

even simpler would be to just remove contact form and just put our email. we can add in contact form later.

2024-07-13 16:43 UTC, marmikpatel19 commented on components/KeyMetrics.tsx
> +    { value: "1st", caption: "Be One of the First Submissions With Fast Track" },
left some comments on discords about fast track

2024-07-14 13:39 UTC, closed without merging

2024-07-14 14:21 UTC, JadeEmm commented on app/page.tsx
> +      <h2 className="text-3xl font-bold mb-0">Join the Agent Success Story</h2>
No, not meant to be a button. Yes, 'Join the Agent Success Story' is targeted towards seekers, as in they will find career/job success by using Agent and be a success story